### ISSUE TITLE
Can't be compared with windows explorer in terms of speed.

### ISSUE THREAD

**Issue by ArjixWasTaken** [conaticus/FileExplorer#2]
Why do I say that? Well, the reason your "explorer" is faster is because it is not up to parity with the windows explorer.

You don't scan for file attributes, that alone is a big time saver that you took, windows search scans for file attributes.
I am all for third party file explorers, but not when they make absurd claims like this.

Yeah you could probably reach feature parity with the windows explorer and still have faster times, but the time savings you did would not be as big as now.

PS: I am not a windows fan boy, and I also hate the windows explorer's search speeds, but that doesn't mean I'll blindly agree that your explorer is faster.

**Comment by ArjixWasTaken** [comment]
I wish you the best and that this project thrives, as I'd like an alternative file explorer that is not a UWP app.

**Comment by 0x454d505459** [comment]
> I wish you the best and that this project thrives, as I'd like an alternative file explorer that is not a UWP app.

An alternative file explorer, which also is a tauri app, you might want to checkout is spacedrive, it's not released yet but you might still be able to compile it. It could also be a great resource for @conaticus.

**Comment by conaticus** [comment]
Hey @ArjixWasTaken, thanks for the feedback. Just got a few questions to confirm what you're saying.

Why would Windows need to search the metadata of every file when someone makes a search? Surely Windows only needs to get the metadata of the files that made a match to the query?

In terms of the query parsing, surely the devs could just modify the iterator so that simpler search queries that don't use any "special syntax" check for less conditions during each iteration?

These are all reasons that could make Windows File Explorer slower, but to me they seem so easily avoidable that it shouldn't be a problem for Windows.

**Comment by ArjixWasTaken** [comment]
> Why would Windows need to search the metadata of every file when someone makes a search? Surely Windows only needs to get the metadata of the files that made a match to the query?

Because you can search for attributes?

For example you can go to a folder with music and search `title: xyz` and it will find a song that has an attribute like that, even if the filename is nothing close to `xyz`.

**Comment by conaticus** [comment]
> For example you can go to a folder with music and search title: xyz and it will find a song that has an attribute like that, even if the filename is nothing close to xyz.

Is it possible to turn that off in Windows? To me it feels like that should be the default option. If I am searching for a file with a title similar to `xyz`, I don't want Windows to find the attributes because I've told it the `title` should match the query "xyz" hence the `title: xyz`. It doesn't matter what the attributes are.

Also I don't think it would be that hard to check the complexity of the query. If the query is plainly "filename" then Windows knows that the user doesn't want to filter anything except for file names. Whether it should search file contents and attributes additionally should be a quickly accessible option in the file explorer imo.

Maybe I'm missing something here but it all seems like a silly reason for Windows file explorer to be slow. I can understand why it would be slow in certain circumstances, if someone really wants to read attributes and file contents. But that should not be the default, that should be an extra options for those that need it.

**Comment by ArjixWasTaken** [comment]
Can't disagree with that
