### ISSUE TITLE
Freeze on loading

### ISSUE THREAD

**Issue by PotatoSUS** [conaticus/FileExplorer#62]
infinite loading 🔥 
![image](https://github.com/conaticus/FileExplorer/assets/82276088/eacd1b3d-2541-40d2-8aa9-8664e093ba34)

**Comment by ismi-abbas** [comment]
My drives indexing time.
![image](https://github.com/conaticus/FileExplorer/assets/77921975/14fa0672-4490-4e69-895f-e90a125fa6ea)

**Comment by grayfallstown** [comment]
I think it should not wait for the index to build before you can access files. Search could block until the index is build or depending how the index is build (first load all files vs add each file to index as soon as it is found) it could show results of what is currently in the index and update the view with new matches as the index is being build up. refs #17

**Comment by RaphGL** [comment]
I think the reason you're having an infinite load is due to this issue https://github.com/conaticus/FileExplorer/issues/41
if you look at [filesystem/cache.rs:133](https://github.com/conaticus/FileExplorer/blob/main/src-tauri/src/filesystem/cache.rs#L133) you can see that the cache has a 60 second interval before a new recaching is started, this means the frontend never gets the volumes it needs to know about and you're stuck on an infinite loop ([filesystem/volume.rs:124](https://github.com/conaticus/FileExplorer/blob/main/src-tauri/src/filesystem/volume.rs#L124))
